### ISSUE TITLE
gt-linalg/overview.xml: Typo:  Muhammad ibn Muso al-Khwarizmi

### ISSUE THREAD

**Issue by arielf** [QBobWatson/gt-linalg#142]
In the file: gt-linalg/overview.xml:

Should be 'Musa' (Moses in Arabic) instead of 'Muso'

Reference:  https://en.wikipedia.org/wiki/Muhammad_ibn_Musa_al-Khwarizmi

**Comment by QBobWatson** [comment]
Good catch -- thank you!
