### ISSUE TITLE
Feedback on matrix-inverses

### ISSUE THREAD

**Issue by blairelee** [QBobWatson/gt-linalg#170]
In reference to version c625deae2631fc33e24b702597b03d9ad5488aef

<img width="674" alt="screen shot 2018-10-24 at 2 51 28 am" src="https://user-images.githubusercontent.com/22570063/47411737-b97dc280-d737-11e8-86fa-3b948654aaf3.png">

There seems an error regarding to the final x value, which is written as (1,2) but actually (-1,2). It is not a critical error, but it is better to be fixed than not fixed!

**Comment by QBobWatson** [comment]
Fixed.  Thank you!
