### ISSUE TITLE
Feedback on eigenvectors

### ISSUE THREAD

**Issue by matthewpleskow** [QBobWatson/gt-linalg#205]
In reference to version 142dea9e612ee3a8970f91e9ccfeb4e98f7a6519
![error](https://user-images.githubusercontent.com/44274985/48222309-49d81c00-e362-11e8-8544-cf9e25d69ff4.PNG)
In this example the value of w changes when it shouldn't.

**Comment by QBobWatson** [comment]
Fixed: thanks!
