### ISSUE TITLE
Feedback on systems-of-eqns

### ISSUE THREAD

**Issue by ceciliajm** [QBobWatson/gt-linalg#254]
Just a few typos I saw:

At least two equations are **need** to define a line in space.
-->At least two equations are needed to define a line in space.

...indeed, every point on the first line **line** has two coordinates, like the point ( 0,1 )... 
-->...indeed, every point on the first line has two coordinates, like the point ( 0,1 )... 

In reference to version 5f9d00240bebd633057eaab6b1d13c8707d3fd73

**Comment by QBobWatson** [comment]
Thank you!
