### ISSUE TITLE
Correction in least-squares

### ISSUE THREAD

**Issue by haerski** [QBobWatson/gt-linalg#255]
In reference to version 5f9d00240bebd633057eaab6b1d13c8707d3fd73
In the example "Infinitely many least squares solutions", in the fourth equation, the signs of +5 and -3 are the wrong way, i.e. the equations should be
x_1 = -x_3 +5
x_2 = 2x_3 + 3
x_3 = x_3

**Comment by QBobWatson** [comment]
Fixed -- thank you!
