### ISSUE TITLE
Feedback on parametric-form

### ISSUE THREAD

**Issue by MiriamKoga** [QBobWatson/gt-linalg#30]
In reference to version d2646db9994db45928275d4074bfb08ddf5a523d

Hi!
On the last matrix from the section 2.3 Parametric Form of your textbook I think that there may be a number 1 missing in the third column.
![image](https://user-images.githubusercontent.com/43017751/45124589-e4d13180-b138-11e8-82e7-1b99ebab71fd.png)

Sorry if I'm wrong and thanks for the awesome material!

Miriam Koga

**Comment by QBobWatson** [comment]
Thank you Miriam for pointing this out!
